services:
  mysql:
    image: mysql:9.2
    container_name: charm-bot-mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - '${DATABASE_PORT}:${DATABASE_PORT}'
    volumes:
      - charm-db-data:/var/lib/mysql
    restart: unless-stopped
    command: --general-log=0
    networks:
      - shared-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: charm-bot-phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=${DATABASE_PORT}
    ports:
      - '${PHPMYADMIN_PORT}:80'
    networks:
      - shared-network
    depends_on:
      - mysql

  redis:
    image: redis:7-alpine
    container_name: charm-bot-redis
    restart: unless-stopped
    ports:
      - '6380:6379'
    volumes:
      - redis-data:/data
    networks:
      - shared-network
    command: redis-server --requirepass pass

networks:
  shared-network:
    driver: bridge
    name: shared-network

volumes:
  charm-db-data:
  redis-data:
